POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=' '
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
POWERLEVEL9K_VCS_GIT_ICON=' '
POWERLEVEL9K_HOME_ICON=' '
POWERLEVEL9K_FOLDER_ICON=' '

POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_DIR_PATH_SEPARATOR='  '
POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(vi_mode dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs)

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{031}\uF460%F{254}\uF460%F{031}\uF460%f "

# Colors

POWERLEVEL9K_OS_ICON_FOREGROUND='252'
POWERLEVEL9K_OS_ICON_BACKGROUND='242'

POWERLEVEL9K_VI_INSERT_MODE_STRING=''
POWERLEVEL9K_VI_COMMAND_MODE_STRING=''
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='254'
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='242'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='237'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='121'


# dir
POWERLEVEL9K_SHORTEN_DELIMITER=''
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_first_and_last'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='252'
POWERLEVEL9K_DIR_HOME_FOREGROUND='252'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='252'
POWERLEVEL9K_DIR_ETC_FOREGROUND='252'
POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND='252'

POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='237'
POWERLEVEL9K_DIR_HOME_BACKGROUND='237'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='237'
POWERLEVEL9K_DIR_ETC_BACKGROUND='237'
POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND='237'

POWERLEVEL9K_VCS_CLEAN_FOREGROUND='232'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='110'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='232'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='139'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='232'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='174'

POWERLEVEL9K_STATUS_CROSS=true
POWERLEVEL9K_STATUS_OK_BACKGROUND='234'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='234'

POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD='0'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='252'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='237'

POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='242'
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='252'

